<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <LangVersion>13</LangVersion>
        <IsPackable>false</IsPackable>
        <SignAssembly>true</SignAssembly>

        <Company>ForOne</Company>
        <AssemblyVersion>0.1.1</AssemblyVersion>
        <FileVersion>0.1.1</FileVersion>
        <SignAssembly>true</SignAssembly>
        <AssemblyOriginatorKeyFile>TrifingZW.snk</AssemblyOriginatorKeyFile>
        <ApplicationIcon>icon.ico</ApplicationIcon>

        <!-- 启用隐式使用指令 -->
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>


    <ItemGroup>
        <ProjectReference Include="..\WatcherCore\WatcherCore.csproj"/>
    </ItemGroup>


    <ItemGroup>
      <PackageReference Include="System.Management" Version="9.0.0" />
    </ItemGroup>

</Project>
